"""
Simulation node — runs the full node agent loop without a real model.

Registers with the orchestrator, accepts jobs, and returns a simulated
response after a realistic delay. Use this to test the full pipeline
before a real model is installed.

Usage:
    NODE_BASE_URL=http://localhost:8001 \
    ORCHESTRATOR_URL=http://localhost:8000 \
    python -m node_agent.simulate
"""

import asyncio
import os
import platform
import time
import textwrap
from contextlib import asynccontextmanager

import httpx
import psutil
from fastapi import FastAPI
from pydantic import BaseModel

NODE_ID       = os.environ.get("NODE_ID", f"sim-{platform.node()}")
ORCH_URL      = os.environ.get("ORCHESTRATOR_URL", "http://localhost:8000")
NODE_BASE_URL = os.environ.get("NODE_BASE_URL", "http://localhost:8001")
API_KEY       = os.environ.get("API_KEY", "")
MODEL_NAME    = "mistral-7b-instruct-v0.2.Q4_K_M"   # pretend we have this loaded

TOKENS_PER_SEC = 35   # realistic M-series throughput for Q4_K_M


class JobRequest(BaseModel):
    job_id: str
    prompt: str
    max_tokens: int = 512
    is_challenge: bool = False


class JobResult(BaseModel):
    job_id: str
    output: str
    tokens_generated: int
    latency_ms: float


def _auth_headers():
    return {"X-Api-Key": API_KEY} if API_KEY else {}


def _simulated_response(prompt: str, max_tokens: int) -> tuple[str, int]:
    """Return a plausible-looking response and token count."""
    short_prompt = prompt.strip()[:120].replace("\n", " ")
    tokens = min(max_tokens, 80)
    response = textwrap.dedent(f"""\
        [SIM] Responding to: "{short_prompt}…"

        This is a simulated inference result from node {NODE_ID}.
        In production this text would be generated by Mistral-7B running
        on Metal via llama.cpp. Approximate throughput: ~{TOKENS_PER_SEC} tok/s.
        Simulated token count: {tokens}.""")
    return response, tokens


async def _register():
    payload = {
        "node_id": NODE_ID,
        "os": "darwin",
        "chip": "apple_m_sim",
        "ram_gb": round(psutil.virtual_memory().total / (1024 ** 3)),
        "max_model": MODEL_NAME,
        "throughput_class": "medium",
        "models_loaded": [MODEL_NAME],
        "base_url": NODE_BASE_URL,
    }
    try:
        async with httpx.AsyncClient(timeout=5) as client:
            r = await client.post(
                f"{ORCH_URL}/nodes/register",
                json=payload,
                headers=_auth_headers(),
            )
            r.raise_for_status()
            print(f"[sim-node] Registered with orchestrator at {ORCH_URL}")
    except Exception as e:
        print(f"[sim-node] Registration failed: {e}")


async def _heartbeat_loop():
    while True:
        await asyncio.sleep(25)
        try:
            async with httpx.AsyncClient(timeout=5) as client:
                await client.post(
                    f"{ORCH_URL}/nodes/{NODE_ID}/heartbeat",
                    headers=_auth_headers(),
                )
        except Exception:
            pass


@asynccontextmanager
async def lifespan(app: FastAPI):
    await _register()
    asyncio.create_task(_heartbeat_loop())
    print(f"[sim-node] Ready — listening on {NODE_BASE_URL}")
    yield


app = FastAPI(title="GPU Cluster Sim Node", lifespan=lifespan)


@app.post("/run", response_model=JobResult)
async def run_job(job: JobRequest) -> JobResult:
    output, tokens = _simulated_response(job.prompt, job.max_tokens)

    # Simulate realistic inference time
    latency_s = tokens / TOKENS_PER_SEC
    await asyncio.sleep(latency_s)

    latency_ms = round(latency_s * 1000, 1)
    print(f"[sim-node] job={job.job_id[:8]}… tokens={tokens} latency={latency_ms}ms")
    return JobResult(
        job_id=job.job_id,
        output=output,
        tokens_generated=tokens,
        latency_ms=latency_ms,
    )


@app.get("/health")
async def health():
    return {
        "node_id": NODE_ID,
        "status": "ready",
        "model_loaded": MODEL_NAME,
        "ram_gb": round(psutil.virtual_memory().total / (1024 ** 3)),
        "mode": "simulation",
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8001)
